parameters:
#    jack_benzaken_cms.example.class: JackBenzaken\CmsBundle\Example

services:
#    jack_benzaken_cms.example:
#        class: %jack_benzaken_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
